name: Node JS CD with Linux Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Master Branch
        run: |
          cd /home/admin/web/vue-nginx-tutorial && sudo git pull origin main

      - name: Deploy with Gradle Build
        run: |
          sudo sh /home/admin/web/vue-nginx-tutorial/deploy.sh